apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    creationTimestamp: "2020-01-09T08:29:26Z"
    generation: 25
    name: test-young
    namespace: admin
    resourceVersion: "8472230"
    selfLink: /apis/apps/v1/namespaces/admin/statefulsets/test-young
    uid: 8cf3d89c-0446-4790-af8a-71d227866e48
  spec:
    podManagementPolicy: OrderedReady
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        statefulset: test-young
    serviceName: ""
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: test-young
          notebook-name: test-young
          statefulset: test-young
      spec:
        containers:
        - args:
          - jupyter notebook --notebook-dir=/home/jovyan --ip=0.0.0.0 --no-browser
            --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password=''
            --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX} --NotebookApp.tornado_settings={headers:{Content-Security-Policy:frame-ancestors
            http://91b714aa.ngrok.io/ 'self' }}
          command:
          - sh
          - -c
          env:
          - name: NB_PREFIX
            value: /notebook/admin/test-young
          - name: DOMAIN
            value: http://ai-demo.test/
          image: gcr.io/kubeflow-images-public/tensorflow-1.13.1-notebook-cpu:v0.5.0
          imagePullPolicy: IfNotPresent
          name: test-young
          ports:
          - containerPort: 8888
            name: notebook-port
            protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /home/jovyan
            name: workspace-test-young
          - mountPath: /home/jovyan/data-vol-1
            name: test-young-vol-1
          - mountPath: /dev/shm
            name: dshm
          workingDir: /home/jovyan
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 100
        serviceAccount: default-editor
        serviceAccountName: default-editor
        terminationGracePeriodSeconds: 30
        volumes:
        - name: workspace-test-young
          persistentVolumeClaim:
            claimName: workspace-test-young
        - name: test-young-vol-1
          persistentVolumeClaim:
            claimName: test-young-vol-1
        - emptyDir:
            medium: Memory
          name: dshm
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
  status:
    collisionCount: 0
    currentRevision: test-young-5b4c5756f9
    observedGeneration: 25
    replicas: 1
    updateRevision: test-young-5f7bc7bc7f
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
